### ISSUE TITLE
想定解とテスト解で出力したトークンの数が異なる場合、  エラーメッセージが不適当なものになる。

### ISSUE THREAD

**Issue by AABCEHM** [givery-technology/marine#25]
marineでソースコードをテストし、その出力が誤っていた場合、

  AssertionError: n番目のデータが違います。
  期待された答え: hoge
  あなたの答え: fuga

というエラーメッセージが表示される。
しかし、想定解とテスト解で出力したトークンの数が異なる場合、出力されるエラーメッセージが不適当なものとなる

- トークン不足の場合
「期待された答え」と「あなたの答え」が共に空欄となる。
- トークン過多の場合
「期待された答え」と「あなたの答え」が共に想定解の最後の出力トークンとなる。

**Comment by hamko** [comment]
Marine ではなくテストランナの不具合のため dup で閉じます。
